categories = [
    'Housing',
    'Utilities',
    'Groceries',
    'Dining Out',
    'Transportation',
    'Life Essentials',
    'Fun',
    'Travel',
    'Entertainment',
    'Subscriptions',
    'Kids and babies',
    'Style and Fitness',
    'Medical',
    'Pet Expenses',
    'Technology',
    'Generosity and Gifts',
    'Insurances, Taxes and Services',
    'Debts',
    'Savings',
]

subcategories = [
    { category_id = 1, name = 'Mortgage' },
    { category_id = 1, name = 'Repairs' },
    { category_id = 1, name = 'Renovations' },
    { category_id = 2, name = 'Electricity' },
    { category_id = 2, name = 'Gas' },
    { category_id = 2, name = 'Internet' },
    { category_id = 2, name = 'Cell Phone' },
    { category_id = 2, name = 'Water' },
    { category_id = 2, name = 'Groceries' },
    { category_id = 4, name = 'Restaurants' },
    { category_id = 5, name = 'Petrol' },
    { category_id = 5, name = 'Repairs' },
    { category_id = 5, name = 'Parking' },
    { category_id = 5, name = 'Tolls' },
    { category_id = 6, name = 'Tools' },
    { category_id = 6, name = 'Furniture' },
    { category_id = 6, name = 'Documents' },
    { category_id = 7, name = 'Bars' },
    { category_id = 8, name = 'Plane Tickets' },
    { category_id = 9, name = 'Concerts' },
    { category_id = 9, name = 'Movies' },
    { category_id = 10, name = 'Netflix' },
    { category_id = 10, name = 'Tidal' },
    { category_id = 10, name = 'Preply' },
    { category_id = 11, name = 'Toys' },
    { category_id = 11, name = 'Allowances' },
    { category_id = 12, name = 'Gym' },
    { category_id = 12, name = 'Hair cut' },
    { category_id = 12, name = 'Clothes' },
    { category_id = 13, name = 'Doctor visit' },
    { category_id = 13, name = 'Dentist visit' },
    { category_id = 13, name = 'Eye Doctor visit' },
    { category_id = 14, name = 'Vet' },
    { category_id = 14, name = 'Food' },
    { category_id = 15, name = 'Cloud' },
    { category_id = 16, name = 'Holidays Gifts' },
    { category_id = 16, name = 'Birthday Gifts' },
    { category_id = 16, name = 'Wedding Gifts' },
    { category_id = 17, name = 'Car Insurance' },
    { category_id = 18, name = 'Credit Card' },
    { category_id = 19, name = 'Emergency Fund' },
]
